---
apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: gardener-extension-envoy-gateway
helm:
  ociRepository:
    ref: registry.local.gardener.cloud:5001/helm-charts/gardener-extension-envoy-gateway:v0.1.0
  values:
    webhook:
      enabled: true
