//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-envoy-gateway/pkg/apis/config"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*config.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_config_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*config.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*config.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataPlaneConfig)(nil), (*config.DataPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DataPlaneConfig_To_config_DataPlaneConfig(a.(*DataPlaneConfig), b.(*config.DataPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DataPlaneConfig)(nil), (*DataPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DataPlaneConfig_To_v1alpha1_DataPlaneConfig(a.(*config.DataPlaneConfig), b.(*DataPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvoyGatewayConfig)(nil), (*config.EnvoyGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnvoyGatewayConfig_To_config_EnvoyGatewayConfig(a.(*EnvoyGatewayConfig), b.(*config.EnvoyGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EnvoyGatewayConfig)(nil), (*EnvoyGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EnvoyGatewayConfig_To_v1alpha1_EnvoyGatewayConfig(a.(*config.EnvoyGatewayConfig), b.(*EnvoyGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvoyProxyDefaults)(nil), (*config.EnvoyProxyDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnvoyProxyDefaults_To_config_EnvoyProxyDefaults(a.(*EnvoyProxyDefaults), b.(*config.EnvoyProxyDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EnvoyProxyDefaults)(nil), (*EnvoyProxyDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EnvoyProxyDefaults_To_v1alpha1_EnvoyProxyDefaults(a.(*config.EnvoyProxyDefaults), b.(*EnvoyProxyDefaults), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_config_ControlPlaneConfig(in *ControlPlaneConfig, out *config.ControlPlaneConfig, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.LogLevel = config.LogLevel(in.LogLevel)
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_config_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_config_ControlPlaneConfig(in *ControlPlaneConfig, out *config.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_config_ControlPlaneConfig(in, out, s)
}

func autoConvert_config_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *config.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.LogLevel = LogLevel(in.LogLevel)
	return nil
}

// Convert_config_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_config_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *config.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_config_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_DataPlaneConfig_To_config_DataPlaneConfig(in *DataPlaneConfig, out *config.DataPlaneConfig, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.LogLevel = config.LogLevel(in.LogLevel)
	return nil
}

// Convert_v1alpha1_DataPlaneConfig_To_config_DataPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_DataPlaneConfig_To_config_DataPlaneConfig(in *DataPlaneConfig, out *config.DataPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DataPlaneConfig_To_config_DataPlaneConfig(in, out, s)
}

func autoConvert_config_DataPlaneConfig_To_v1alpha1_DataPlaneConfig(in *config.DataPlaneConfig, out *DataPlaneConfig, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.LogLevel = LogLevel(in.LogLevel)
	return nil
}

// Convert_config_DataPlaneConfig_To_v1alpha1_DataPlaneConfig is an autogenerated conversion function.
func Convert_config_DataPlaneConfig_To_v1alpha1_DataPlaneConfig(in *config.DataPlaneConfig, out *DataPlaneConfig, s conversion.Scope) error {
	return autoConvert_config_DataPlaneConfig_To_v1alpha1_DataPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_EnvoyGatewayConfig_To_config_EnvoyGatewayConfig(in *EnvoyGatewayConfig, out *config.EnvoyGatewayConfig, s conversion.Scope) error {
	out.ControlPlane = (*config.ControlPlaneConfig)(unsafe.Pointer(in.ControlPlane))
	out.DataPlane = (*config.DataPlaneConfig)(unsafe.Pointer(in.DataPlane))
	out.Channel = config.Channel(in.Channel)
	out.ManageCRDs = (*bool)(unsafe.Pointer(in.ManageCRDs))
	out.EnvoyProxyDefaults = (*config.EnvoyProxyDefaults)(unsafe.Pointer(in.EnvoyProxyDefaults))
	return nil
}

// Convert_v1alpha1_EnvoyGatewayConfig_To_config_EnvoyGatewayConfig is an autogenerated conversion function.
func Convert_v1alpha1_EnvoyGatewayConfig_To_config_EnvoyGatewayConfig(in *EnvoyGatewayConfig, out *config.EnvoyGatewayConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnvoyGatewayConfig_To_config_EnvoyGatewayConfig(in, out, s)
}

func autoConvert_config_EnvoyGatewayConfig_To_v1alpha1_EnvoyGatewayConfig(in *config.EnvoyGatewayConfig, out *EnvoyGatewayConfig, s conversion.Scope) error {
	out.ControlPlane = (*ControlPlaneConfig)(unsafe.Pointer(in.ControlPlane))
	out.DataPlane = (*DataPlaneConfig)(unsafe.Pointer(in.DataPlane))
	out.Channel = Channel(in.Channel)
	out.ManageCRDs = (*bool)(unsafe.Pointer(in.ManageCRDs))
	out.EnvoyProxyDefaults = (*EnvoyProxyDefaults)(unsafe.Pointer(in.EnvoyProxyDefaults))
	return nil
}

// Convert_config_EnvoyGatewayConfig_To_v1alpha1_EnvoyGatewayConfig is an autogenerated conversion function.
func Convert_config_EnvoyGatewayConfig_To_v1alpha1_EnvoyGatewayConfig(in *config.EnvoyGatewayConfig, out *EnvoyGatewayConfig, s conversion.Scope) error {
	return autoConvert_config_EnvoyGatewayConfig_To_v1alpha1_EnvoyGatewayConfig(in, out, s)
}

func autoConvert_v1alpha1_EnvoyProxyDefaults_To_config_EnvoyProxyDefaults(in *EnvoyProxyDefaults, out *config.EnvoyProxyDefaults, s conversion.Scope) error {
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.AccessLogging = in.AccessLogging
	return nil
}

// Convert_v1alpha1_EnvoyProxyDefaults_To_config_EnvoyProxyDefaults is an autogenerated conversion function.
func Convert_v1alpha1_EnvoyProxyDefaults_To_config_EnvoyProxyDefaults(in *EnvoyProxyDefaults, out *config.EnvoyProxyDefaults, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnvoyProxyDefaults_To_config_EnvoyProxyDefaults(in, out, s)
}

func autoConvert_config_EnvoyProxyDefaults_To_v1alpha1_EnvoyProxyDefaults(in *config.EnvoyProxyDefaults, out *EnvoyProxyDefaults, s conversion.Scope) error {
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.AccessLogging = in.AccessLogging
	return nil
}

// Convert_config_EnvoyProxyDefaults_To_v1alpha1_EnvoyProxyDefaults is an autogenerated conversion function.
func Convert_config_EnvoyProxyDefaults_To_v1alpha1_EnvoyProxyDefaults(in *config.EnvoyProxyDefaults, out *EnvoyProxyDefaults, s conversion.Scope) error {
	return autoConvert_config_EnvoyProxyDefaults_To_v1alpha1_EnvoyProxyDefaults(in, out, s)
}
