//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneConfig) DeepCopyInto(out *ControlPlaneConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneConfig.
func (in *ControlPlaneConfig) DeepCopy() *ControlPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPlaneConfig) DeepCopyInto(out *DataPlaneConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPlaneConfig.
func (in *DataPlaneConfig) DeepCopy() *DataPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(DataPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyGatewayConfig) DeepCopyInto(out *EnvoyGatewayConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(ControlPlaneConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DataPlane != nil {
		in, out := &in.DataPlane, &out.DataPlane
		*out = new(DataPlaneConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ManageCRDs != nil {
		in, out := &in.ManageCRDs, &out.ManageCRDs
		*out = new(bool)
		**out = **in
	}
	if in.EnvoyProxyDefaults != nil {
		in, out := &in.EnvoyProxyDefaults, &out.EnvoyProxyDefaults
		*out = new(EnvoyProxyDefaults)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyGatewayConfig.
func (in *EnvoyGatewayConfig) DeepCopy() *EnvoyGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(EnvoyGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyGatewayConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyProxyDefaults) DeepCopyInto(out *EnvoyProxyDefaults) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyProxyDefaults.
func (in *EnvoyProxyDefaults) DeepCopy() *EnvoyProxyDefaults {
	if in == nil {
		return nil
	}
	out := new(EnvoyProxyDefaults)
	in.DeepCopyInto(out)
	return out
}
