//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&EnvoyGatewayConfig{}, func(obj interface{}) { SetObjectDefaults_EnvoyGatewayConfig(obj.(*EnvoyGatewayConfig)) })
	return nil
}

func SetObjectDefaults_EnvoyGatewayConfig(in *EnvoyGatewayConfig) {
	SetDefaults_EnvoyGatewayConfig(in)
	if in.ControlPlane != nil {
		SetDefaults_ControlPlaneConfig(in.ControlPlane)
	}
	if in.DataPlane != nil {
		SetDefaults_DataPlaneConfig(in.DataPlane)
	}
}
